const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const app = express();
const port = 8001;

app.listen(port);

let dictionary = [
  //nouns
  { word: "Thou", synonyms: ["You"] },
  { word: "thou", synonyms: ["you"] },
  { word: "Thine", synonyms: ["Your"] },
  { word: "thine", synonyms: ["your"] },
  { word: "Thyself", synonyms: ["Yourself"] },
  { word: "thyself", synonyms: ["yourself"] },
  { word: "Aught", synonyms: ["Anything", "Zero"] },
  { word: "aught", synonyms: ["anything", "zero"] },
  { word: "thrice", synonyms: ["three times", "3 times"] },
  { word: "Thrice", synonyms: ["Three times"] },
  {
    word: "Influx",
    synonyms: [
      "Inflow",
      "Inrush",
      "Rush",
      "Stream",
      "Flood",
      "Incursion",
      "Ingress",
      "Invasion",
      "Intrusion",
    ],
  },
  {
    word: "influx",
    synonyms: [
      "inflow",
      "inrush",
      "rush",
      "stream",
      "flood",
      "incursion",
      "ingress",
      "invasion",
      "intrusion",
    ],
  },
  {
    word: "Paraphernailia",
    synonyms: [
      "Equipment",
      "Stuff",
      "Things",
      "Apparatus",
      "Tackle",
      "Kit",
      "Implements",
      "Tools",
      "Utensils",
      "Material",
      "Materials",
      "Appliances",
      "Rig",
      "Outfit",
      "Accoutrements",
      "Appurtenances",
      "Impedimenta",
      "Miscellaneous articles",
      "Odds and ends",
      "Bits and pieces",
      "Bits and bobs",
      "Trappings",
      "Accessories",
      "Rubbish",
      "Gear",
      "Junk",
      "Traps",
    ],
  },
  {
    word: "paraphernailia",
    synonyms: [
      "equipment",
      "stuff",
      "things",
      "apparatus",
      "tackle",
      "kit",
      "implements",
      "tools",
      "utensils",
      "material",
      "materials",
      "appliances",
      "rig",
      "outfit",
      "accoutrements",
      "appurtenances",
      "impedimenta",
      "miscellaneous articles",
      "odds and ends",
      "bits and pieces",
      "bits and bobs",
      "trappings",
      "accessories",
      "rubbish",
      "gear",
      "junk",
      "traps",
    ],
  },
  {
    word: "Zenith",
    synonyms: [
      "Highest point",
      "High point",
      "Crowning point",
      "Peak",
      "Maximum",
      "Prime",
    ],
  },
  {
    word: "zenith",
    synonyms: [
      "highest point",
      "high point",
      "crowning point",
      "peak",
      "maximum",
      "prime",
    ],
  },
  {
    word: "Myriads of",
    synonyms: [
      "Multitude of",
      "Countless",
      "Innumerable",
      "Numerous",
      "A large number of",
      "A great number of",
      "A lot of",
      "Loads of",
      "Tons of",
      "Hundreds of",
      "Thousands of",
      "Millions of",
      "Billions of",
      "Zillions of",
    ],
  },
  {
    word: "myriads of",
    synonyms: [
      "multitude of",
      "countless",
      "innumerable",
      "numerous",
      "a large number of",
      "a great number of",
      "a lot of",
      "loads of",
      "tons of",
      "hundreds of",
      "thousands of",
      "millions of",
      "billions of",
      "zillions of",
    ],
  },
  { word: "maxim", synonyms: ["saying", "motto", "slogan"] },
  { word: "A maxim", synonyms: ["A saying"] },
  { word: "a maxim", synonyms: ["a saying"] },
  { word: "The maxim", synonyms: ["The saying"] },
  { word: "the maxim", synonyms: ["the saying"] },
  //adjectives/verbes
  { word: "pulchritudinous", synonyms: ["beautiful"] },
  {
    word: "frivolous",
    synonyms: [
      "giddy",
      "silly",
      "foolish",
      "facetious",
      "zany",
      "lighthearted",
      "merry",
      "superficial",
      "shallow",
      "lacking seriousness",
      "nonserious",
      "light-minded",
      "whimsical",
      "skittish",
      "flighty",
      "irresponsible",
      "thoughtless",
      "lacking in sense",
      "featherbrained",
      "empty-headed",
      "peabrained",
      "birdbrained",
      "vacuous",
      "vapid",
      "dizzy",
      "dippy",
      "dopey",
      "nutty",
    ],
  },
];

app.post("/fancyficate", async (req, res) => {
  //code
  res.status(200).json({ result: "test test" });
});
